# Please enter your MySQL information below. These need to be the same as for PlayerServers.
mysql:
  # Url of the MySQL server, in format: jdbc:mysql://<host>:<port>/<database>
  # Any additional options can be added at the end of url, such as:
  # ?autoReconnect=true&useSSL=false?useUnicode=true&characterEncoding=UTF-8
  url: "jdbc:mysql://localhost:3306/playerservers?useSSL=false&serverTimezone=UTC"

  username: root
  password: root

  # Developer options, do not change unless you know what you are doing.
  driver: "com.mysql.cj.jdbc.Driver"
  update-policy: "update"
  debug: false
  get-from-file: false

# For how long should we keep Server Data cached?
cache-time: 20

messages:
  no-permission: "&9Error> &7Oops, it seems like you don't have permission to do that."

gui:
  selector:
    enabled: true

    item:
      enabled: true
      name: "&aQuick Compass"
      material: "COMPASS"
      location: 0
      description:
        - "&7Click here to open the server"
        - "&7selector or to create your own one"

    menu:
      name: "&aServer Selector"
      online:
        block: "PLAYER_HEAD"
        name: '&a%server%''s server'
        lore:
          - '&7Status: %status%'
          - '&7Players: &2%players%&8/&a%maxplayers%'
          - '&7Owner: &a%owner%'
          - '&7Motd: &a%motd%'
          - '&7Node: &a%node%'
          - '&7Ip: &a%ip%&8:&a%port%'
      offline:
        block: "RED_TERRACOTTA"
        name: '&c%server%''s server'
        lore:
          - '&7Status: %status%'
          - '&7Owner: &c%owner%'
          - '&7Node: &c%node%'
          - '&7Ip: &c%ip%&8:&c%port%'

  player-menu:
    enabled: true

    item:
      enabled: true
      name: "&eMy Server"
      material: "EMERALD"
      location: 8
      description:
        - "&7Click here to open the server"
        - "&7selector or to create your own one"

    menu:
      name: "&eMy Server"
      info:
        online:
          name: '&a%server%''s server'
          lore:
            - '&7Status: %status%'
            - '&7Players: &2%players%&8/&a%maxplayers%'
            - '&7Owner: &a%owner%'
            - '&7Motd: &a%motd%'
            - '&7Node: &a%node%'
            - '&7Ip: &a%ip%&8:&a%port%'
        offline:
          name: '&c%server%''s server'
          lore:
            - '&7Status: %status%'
            - '&7Owner: &c%owner%'
            - '&7Node: &c%node%'
            - '&7Ip: &c%ip%&8:&c%port%'
      create:
        name: "&aCreate a new server"
        lore:
          - "&7Click here to create a new server"
      delete:
        name: "&cDelete the server"
        lore:
          - "&7Click here to delete the server"
        confirmation:
          name: "&cDelete this server?"
          accept:
            name: "&cAre you sure?"
            lore:
              - "&7Click here to confirm"
              - "&7deletion of your server."
              - "&7All files will be deleted"
              - "&7forever without possibility"
              - "&7to restore them."
          decline:
            name: "&cNo, I'm not sure"
            lore:
              - "&7Click here to cancel"
              - "&7deletion of your server."

      join:
        name: "&aJoin the server"
        lore:
          - "&7Click here to join the server"
      stop:
        name: "&cStop the server"
        lore:
          - "&7Click here to stop the server"
        confirmation:
          name: "&cStop this server?"
          accept:
            name: "&cAre you sure?"
            lore:
              - "&7Click here to confirm"
              - "&7stopping your server."
          decline:
            name: "&cNo, I'm not sure"
            lore:
              - "&7Click here to cancel"
              - "&7stopping your server."
      start:
        name: "&aStart the server"
        lore:
          - "&7Click here to start the server"

# Should we enable multinode support?
multi-node: false

miscellaneous:
  # Should we disable weather events?
  disable-weather: true

  # Should we disable damage on the server
  disable-damage: true