name: PSHubCore
main: os.arcadiadevs.playerservers.hubcore.PSHubCore
version: v3-dev
author: OpenSource

softdepend: [PlaceholderAPI]

commands:
  servers:
    usage: /servers
    description: Opens up server selector GUI
    aliases:
      - menu
      - opengui