name: PSHubCore
main: os.arcadiadevs.playerservers.hubcore.PsHubCore
version: 3-dev
author: OpenSource

softdepend: [PlaceholderAPI]

commands:
  servers:
    usage: /servers
    description: Opens up server selector GUI
    aliases:
      - menu
      - opengui