name: PSHubCore
main: os.arcadiadevs.playerservers.hubcore.PsHubCore
version: 3-dev
author: OpenSource

softdepend: [PlaceholderAPI]

commands:
  servers:
    usage: /servers
    description: Opens up server selector GUI
    aliases:
      - opengui
  playermenu:
    usage: /playermenu
    description: Opens up player-menu GUI
    aliases:
      - pmenu
      - playergui
  adminmenu:
    usage: /adminmenu
    description: Opens up admin-menu GUI
    aliases:
      - adminmenu