name: PSHubCore
main: os.arcadiadevs.playerservers.hubcore.PSHubCore
version: 3-dev
author: OpenSource

softdepend: [PlaceholderAPI]

commands:
  servers:
    usage: /servers
    description: Opens up server selector GUI
    aliases:
      - menu
      - opengui
  playermenu:
    usage: /playermenu
    description: Opens up player-menu GUI
    aliases:
      - pmenu