mysql:
  hostname: 127.0.0.1
  username: web
  password: webmaster
  database: playerservers
  useSSL: true

enable-compass: true
compass-name: "&aQuick Compass"
compass-location: 0
compass-description:
  - "&7Click here to open the server"
  - "&7selector or to create your own one"

disable-weather: true
disable-damage: true